"""Add container_number to containers

Revision ID: 058953da9209
Revises: 
Create Date: 2025-06-23 21:16:41.978408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058953da9209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_number', sa.String(length=50), nullable=True))
    
    # Add default container numbers for existing containers
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM container ORDER BY id"))
    containers = result.fetchall()
    
    for i, container in enumerate(containers, 1):
        container_id = container[0]
        container_number = str(i)
        connection.execute(
            sa.text("UPDATE container SET container_number = :container_number WHERE id = :id"),
            {'container_number': container_number, 'id': container_id}
        )
    
    # Now add the unique constraint
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_container_container_number', ['container_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_constraint('uq_container_container_number', type_='unique')
        batch_op.drop_column('container_number')

    # ### end Alembic commands ###
