"""Make container_number optional

Revision ID: d68abccad5b0
Revises: 058953da9209
Create Date: 2025-06-23 21:28:25.003963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68abccad5b0'
down_revision = '058953da9209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The unique constraint already exists, so this migration is effectively a no-op
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
